version: '3.1'

services:

  redis:
    container_name: redis
    image: bitnami/redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    networks:
      - net

networks:
  net:
    driver: bridge
