# Generated by Django 3.1.3 on 2020-12-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('port', models.CharField(max_length=50)),
                ('activation', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('temp_register', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fermentazione.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Fermentation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('max_temp', models.FloatField(default=22.0)),
                ('min_temp', models.FloatField(default=18.0)),
                ('sensors', models.ManyToManyField(blank=True, to='fermentazione.Sensor')),
            ],
        ),
    ]
