# Generated by Django 3.1.3 on 2020-12-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fermentazione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('activation', models.BooleanField()),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fermentazione.register')),
            ],
        ),
    ]
